---
- name: "pppd | Include pre requisite tasks"
  ansible.builtin.import_tasks:
    file: "pre_requisite.yml"
- name: "pppd | Stop and disable absent ppp links"
  ansible.builtin.systemd:
    name: "{{ hostvars[inventory_hostname]['pppd_service'] ~ item }}"
    state: "stopped"
    enabled: false
    daemon_reload: true
  loop: "{{ pppd_absent_links | default([]) }}"
  failed_when: false
  when:
    - "pppd_absent_links | default([]) not in ['', [], None]"

- name: "pppd | Remove absent ppp peer files"
  ansible.builtin.file:
    path: "{{ hostvars[inventory_hostname]['pppd_dest'] + '/peers/' ~ item }}"
    state: "absent"
  loop: "{{ pppd_absent_links | default([]) }}"
  when:
    - "pppd_absent_links | default([]) not in ['', [], None]"

- name: "pppd | Remove absent ppp ifup hooks"
  ansible.builtin.file:
    path: "{{ hostvars[inventory_hostname]['pppd_dest'] + '/ip-up.d/' ~ item }}"
    state: "absent"
  loop: "{{ (pppd_absent_links | default([])) +
    ((pppd_absent_links | default([])) | map('regex_replace', '$', '.sh') | list) }}"
  when:
    - "pppd_absent_links | default([]) not in ['', [], None]"

- name: "pppd | Remove absent ppp ifdown hooks"
  ansible.builtin.file:
    path: "{{ hostvars[inventory_hostname]['pppd_dest'] + '/ip-down.d/' ~ item }}"
    state: "absent"
  loop: "{{ (pppd_absent_links | default([])) +
    ((pppd_absent_links | default([])) | map('regex_replace', '$', '.sh') | list) }}"
  when:
    - "pppd_absent_links | default([]) not in ['', [], None]"

- name: "pppd | Remove absent ppp systemd override directories"
  ansible.builtin.file:
    path: "{{ '/etc/systemd/system/' ~
      hostvars[inventory_hostname]['pppd_service'] ~ item ~ '.service.d' }}"
    state: "absent"
  loop: "{{ pppd_absent_links | default([]) }}"
  notify:
    - "Reload systemd daemon"
  when:
    - "pppd_absent_links | default([]) not in ['', [], None]"

- name: "pppd | Include packages tasks"
  ansible.builtin.include_tasks:
    file: "packages.yml"
  when:
    - "hostvars[inventory_hostname]['pppd'] is defined"
    - "hostvars[inventory_hostname]['pppd'] != ''"
    - "hostvars[inventory_hostname]['pppd'] |
      community.general.json_query(vars['pppd_install_package']) is defined"
    - "hostvars[inventory_hostname]['pppd'] |
      community.general.json_query(vars['pppd_install_package']) == 'true'"
  vars:
    pppd_install_package: "[] | map(&install_package || 'false', @) | [0]"
- name: "pppd | Include deployment tasks"
  ansible.builtin.include_tasks:
    file: "pppd_executor.yml"
  when:
    - "vars['pppd_links'] is defined"
    - "vars['pppd_links'] not in ['', [], None]"
- name: Create chap-secrets for PPTP connections
  template:
    src: chap_secrets.j2
    dest: /etc/ppp/chap-secrets
    mode: '0600'
  when: pppd_settings | selectattr('pty', 'defined') | list | length > 0
  notify: "Restart pppd link"
