---
- name: "pppd | Include pre requisite tasks"
  ansible.builtin.import_tasks:
    file: "pre_requisite.yml"
- name: "pppd | Include packages tasks"
  ansible.builtin.include_tasks:
    file: "packages.yml"
  when:
    - "hostvars[inventory_hostname]['pppd'] is defined"
    - "hostvars[inventory_hostname]['pppd'] != ''"
    - "hostvars[inventory_hostname]['pppd'] |
      community.general.json_query(vars['pppd_install_package']) is defined"
    - "hostvars[inventory_hostname]['pppd'] |
      community.general.json_query(vars['pppd_install_package']) == 'true'"
  vars:
    pppd_install_package: "[] | map(&install_package || 'false', @) | [0]"
- name: "pppd | Include deployment tasks"
  ansible.builtin.include_tasks:
    file: "pppd_executor.yml"
  when:
    - "vars['pppd_links'] is defined"
    - "vars['pppd_links'] not in ['', [], None]"
- name: Create chap-secrets for PPTP connections
  template:
    src: chap_secrets.j2
    dest: /etc/ppp/chap-secrets
    mode: '0600'
  when: pppd_settings | selectattr('pty', 'defined') | list | length > 0
  notify: restart pptp services

- name: Ensure systemd overrides for PPTP connections
  template:
    src: pppd_service_override.j2
    dest: "/etc/systemd/system/ppp@{{ item.linkname }}.service.d/override.conf"
    mode: '0644'
  loop: "{{ pppd_settings | selectattr('systemd_override', 'defined') | selectattr('systemd_override', 'equalto', 'true') | list }}"
  when: 
    - item.systemd_override | bool
    - item.pty is defined
  notify: daemon reload